name: Building jless for termux
run-name: ${{ github.actor }} is building jless for termux
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-for-termux:
    runs-on: ubuntu-latest
    steps:
      - name: Preparing repository
        uses: actions/checkout@v4
      - name: Building package
        id: build-package
        run: |
          cd ${{ github.workspace }}
          sh build.sh
      - name: Creating release
        id: create-release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{ github.workspace }}
          TAG="$(git describe --tag)"
          OUTDIR="./termux-packages/output"
          gh release create "$TAG" --verify-tag --generate-notes
          gh release upload "$TAG" "$OUTDIR"/jless*
